<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Report card — {{ $student->name }}</title>
<style>body{font:16px system-ui;color:#302b29;background:#fff;margin:24px auto;padding:16px;max-width:960px}h1{color:#725752}p{line-height:1.7}.summary{background:#d4dfc7;padding:18px;border-radius:12px}.attendance{margin:24px 0;padding:18px;border:1px solid #d4dfc7;border-radius:12px}.attendance h3{margin:0 0 14px;color:#725752}.attendance-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.attendance-grid div{padding:12px;background:#f4f7f0;border-radius:9px}.attendance-grid strong,.attendance-grid small{display:block}.attendance-grid small{margin-top:4px;color:#656c64;font-size:.78rem}.table-wrap{overflow:auto;margin:24px 0}table{width:100%;border-collapse:collapse;min-width:600px}th,td{padding:12px;text-align:left;border-bottom:1px solid #d4dfc7}.actions{display:flex;gap:12px;flex-wrap:wrap}button,a{padding:13px;background:#725752;color:#fff;border:0;border-radius:8px;font:inherit;text-decoration:none;cursor:pointer}.warning{background:#fef6c9;padding:16px}@media(max-width:700px){.attendance-grid{grid-template-columns:repeat(2,1fr)}}@media print{body{margin:0;font-size:11pt}.actions{display:none}.table-wrap{overflow:visible}table{min-width:0}tr{break-inside:avoid}thead{display:table-header-group}}</style></head>
<body><h1>{{ $school }}</h1><h2>Report card: {{ $exam->name }}</h2><p><strong>{{ $student->name }}</strong> · Admission {{ $student->admission_number }}<br>{{ $class }} · Exam date {{ $exam->date }}</p>
@if($exam->status !== 'published')<p class="warning">DRAFT — This report has not been published to the family.</p>@endif
@if(!$complete)<p class="warning">{{ $planned ? 'Incomplete report: some planned marks are missing or unplanned subjects need review. An overall result is not calculated.' : 'Subject results only: no complete exam subject plan was configured. An overall result is not calculated.' }}</p>@endif
<section class="attendance"><h3>Attendance up to exam date</h3><div class="attendance-grid"><div><strong>{{ $attendance['total'] }}</strong><small>Recorded days</small></div><div><strong>{{ $attendance['present'] }}</strong><small>Present / late</small></div><div><strong>{{ $attendance['absent'] }}</strong><small>Absent</small></div><div><strong>{{ $attendance['excused'] }}</strong><small>Excused</small></div><div><strong>{{ $attendance['percentage'] !== null ? number_format($attendance['percentage'], 2).'%' : '—' }}</strong><small>Attendance rate</small></div></div></section>
<div class="table-wrap"><table><thead><tr><th>Subject</th><th>Marks</th><th>Maximum</th><th>Weight</th><th>Percentage</th><th>Grade</th><th>GPA points</th></tr></thead><tbody>
@forelse($rows as $row)<tr><th>{{ $row['name'] }}</th><td>{{ $row['marks'] ?? 'Missing' }}</td><td>{{ $row['maximum'] }}</td><td>{{ $row['weight'] }}</td><td>{{ $row['percentage'] !== null ? number_format($row['percentage'], 2).'%' : '—' }}</td><td>{{ $row['band'] ?? 'Not graded' }}</td><td>{{ $row['gpa'] !== null ? number_format($row['gpa'], 2) : '—' }}</td></tr>
@if($row['remarks'])<tr><td colspan="7">{{ $row['name'] }} remarks: {{ $row['remarks'] }}</td></tr>@endif
@empty<tr><td colspan="7">No subjects or marks have been recorded.</td></tr>@endforelse
</tbody></table></div>
@if($complete)<div class="summary"><strong>Weighted overall result: {{ number_format($percentage, 2) }}%</strong><p>Overall grade: {{ $overallBand ?? 'Not configured' }}<br>Weighted GPA: {{ $gpa !== null ? number_format($gpa, 2) : 'Not configured' }}</p></div>@endif
<p>Overall percentage is the weighted average of subject percentages. GPA is the weighted average of each subject's configured grade points. Missing marks are never treated as zero. Published grading rules are retained with the exam.</p>
<div class="actions"><button onclick="window.print()">Print / save PDF</button><a href="{{ route('dashboard') }}">Back to workspace</a></div></body></html>
