<?php

return [
    'academic_years' => [
        'label' => 'Academic years',
        'singular' => 'academic year',
        'help' => 'Set the start and end dates before creating classes for a new school year.',
        'read' => ['owner', 'admin'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'name',
            'label' => 'Name',
            'type' => 'text',
        ], [
            'name' => 'starts_on',
            'label' => 'Starts on',
            'type' => 'date',
        ], [
            'name' => 'ends_on',
            'label' => 'Ends on',
            'type' => 'date',
        ]],
    ],
    'classes' => [
        'label' => 'Classes & sections',
        'singular' => 'class',
        'help' => 'Create one class for each section, for example Grade 5 A. Each class belongs to an academic year.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent', 'accountant'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'name',
            'label' => 'Class and section',
            'type' => 'text',
        ], [
            'name' => 'year_id',
            'label' => 'Academic year',
            'type' => 'relation',
            'relation' => 'academic_years',
        ], [
            'name' => 'capacity',
            'label' => 'Capacity',
            'type' => 'number',
            'min' => 1,
            'max' => 500,
        ]],
    ],
    'subjects' => [
        'label' => 'Subjects',
        'singular' => 'subject',
        'help' => 'Create the subjects taught at your school, then assign teachers to class subjects.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent', 'accountant'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'name',
            'label' => 'Subject name',
            'type' => 'text',
        ], [
            'name' => 'code',
            'label' => 'Subject code',
            'type' => 'text',
        ]],
    ],
    'staff' => [
        'label' => 'Staff directory',
        'singular' => 'staff member',
        'help' => 'Keep staff employment information here. A staff profile and a sign-in account are separate; link an invited account when available.',
        'read' => ['owner', 'admin'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'name',
            'label' => 'Full name',
            'type' => 'text',
        ], [
            'name' => 'employee_number',
            'label' => 'Employee number',
            'type' => 'text',
        ], [
            'name' => 'department',
            'label' => 'Department',
            'type' => 'text',
        ], [
            'name' => 'designation',
            'label' => 'Job title',
            'type' => 'text',
        ], [
            'name' => 'user_id',
            'label' => 'Sign-in account',
            'type' => 'relation',
            'relation' => 'users',
            'optional' => true,
        ], [
            'name' => 'joined_on',
            'label' => 'Joining date',
            'type' => 'date',
        ], [
            'name' => 'status',
            'label' => 'Status',
            'type' => 'select',
            'choices' => ['active', 'left'],
        ], [
            'name' => 'basic_salary',
            'label' => 'Monthly basic salary',
            'type' => 'money',
            'optional' => true,
        ], [
            'name' => 'monthly_allowances',
            'label' => 'Monthly allowances',
            'type' => 'money',
            'optional' => true,
        ], [
            'name' => 'monthly_deductions',
            'label' => 'Monthly deductions',
            'type' => 'money',
            'optional' => true,
        ]],
    ],
    'staff_attendance' => [
        'label' => 'Staff attendance', 'singular' => 'staff attendance record', 'help' => 'Record daily staff attendance and late arrivals. Staff can see their own history.',
        'read' => ['owner', 'admin', 'teacher'], 'write' => ['owner', 'admin', 'teacher'],
        'fields' => [[ 'name' => 'user_id', 'label' => 'Staff member', 'type' => 'relation', 'relation' => 'users' ], [ 'name' => 'date', 'label' => 'Date', 'type' => 'date' ], [ 'name' => 'status', 'label' => 'Status', 'type' => 'select', 'choices' => ['present', 'late', 'absent', 'leave'] ], [ 'name' => 'check_in', 'label' => 'Check-in time', 'type' => 'time', 'optional' => true ], [ 'name' => 'note', 'label' => 'Note', 'type' => 'textarea', 'optional' => true ]],
    ],
    'students' => [
        'label' => 'Students',
        'singular' => 'student',
        'help' => 'Register a student and assign a class. Student sign-in is optional. Connect guardians separately after verifying the relationship.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent', 'accountant'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'name',
            'label' => 'Full name',
            'type' => 'text',
        ], [
            'name' => 'admission_number',
            'label' => 'Admission number',
            'type' => 'text',
        ], [
            'name' => 'class_id',
            'label' => 'Current class',
            'type' => 'relation',
            'relation' => 'classes',
        ], [
            'name' => 'date_of_birth',
            'label' => 'Date of birth',
            'type' => 'date',
            'optional' => true,
        ], [
            'name' => 'emergency_contact',
            'label' => 'Emergency contact',
            'type' => 'text',
            'optional' => true,
        ], [
            'name' => 'user_id',
            'label' => 'Student sign-in account',
            'type' => 'relation',
            'relation' => 'users',
            'optional' => true,
        ], [
            'name' => 'status',
            'label' => 'Status',
            'type' => 'select',
            'choices' => ['active', 'withdrawn', 'graduated'],
        ]],
    ],
    'student_welfare' => [
        'label' => 'Student welfare',
        'singular' => 'welfare record',
        'help' => 'Keep private medical and behavior notes for authorized school leadership. These records are never shown to parents, students or teachers.',
        'read' => ['owner', 'admin'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'record_type',
            'label' => 'Record type',
            'type' => 'select',
            'choices' => ['medical', 'behavior'],
        ], [
            'name' => 'record_date',
            'label' => 'Record date',
            'type' => 'date',
        ], [
            'name' => 'details',
            'label' => 'Details',
            'type' => 'textarea',
        ], [
            'name' => 'follow_up',
            'label' => 'Follow-up action',
            'type' => 'textarea',
            'optional' => true,
        ]],
    ],
    'guardian_links' => [
        'label' => 'Guardian links',
        'singular' => 'guardian link',
        'help' => 'Verify the guardian with the school before connecting an account to a child. This link gives that guardian access to the child’s published records.',
        'read' => ['owner', 'admin'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'user_id',
            'label' => 'Guardian account',
            'type' => 'relation',
            'relation' => 'users',
        ], [
            'name' => 'relationship',
            'label' => 'Relationship',
            'type' => 'text',
        ], [
            'name' => 'status',
            'label' => 'Access',
            'type' => 'select',
            'choices' => ['active', 'revoked'],
        ]],
    ],
    'teacher_assignments' => [
        'label' => 'Teaching assignments',
        'singular' => 'teaching assignment',
        'help' => 'Assign a teacher to a class and subject. Teachers can enter attendance for their classes and marks for their subjects.',
        'read' => ['owner', 'admin', 'teacher'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'user_id',
            'label' => 'Teacher account',
            'type' => 'relation',
            'relation' => 'users',
        ], [
            'name' => 'class_id',
            'label' => 'Class',
            'type' => 'relation',
            'relation' => 'classes',
        ], [
            'name' => 'subject_id',
            'label' => 'Subject',
            'type' => 'relation',
            'relation' => 'subjects',
        ], [
            'name' => 'status',
            'label' => 'Assignment',
            'type' => 'select',
            'choices' => ['active', 'ended'],
        ]],
    ],
    'materials' => [
        'label' => 'Class materials',
        'singular' => 'material',
        'help' => 'Publish syllabus notes, reading links and class resources for students and parents.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin', 'teacher'],
        'fields' => [[
            'name' => 'class_id',
            'label' => 'Class',
            'type' => 'relation',
            'relation' => 'classes',
        ], [
            'name' => 'subject_id',
            'label' => 'Subject',
            'type' => 'relation',
            'relation' => 'subjects',
        ], [
            'name' => 'teacher_id',
            'label' => 'Teacher account',
            'type' => 'relation',
            'relation' => 'users',
        ], [
            'name' => 'title',
            'label' => 'Title',
            'type' => 'text',
        ], [
            'name' => 'description',
            'label' => 'Description',
            'type' => 'textarea',
        ], [
            'name' => 'resource_url',
            'label' => 'Resource link',
            'type' => 'text',
            'optional' => true,
        ], [
            'name' => 'status',
            'label' => 'Visibility',
            'type' => 'select',
            'choices' => ['draft', 'published'],
        ]],
    ],
    'submissions' => [
        'label' => 'Assignment submissions',
        'singular' => 'submission',
        'help' => 'Students submit published assignments here. Teachers can review submissions, record a grade and return feedback. Optional private PDF, Word or image attachments are supported.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin', 'teacher', 'student'],
        'fields' => [[
            'name' => 'assignment_id',
            'label' => 'Assignment',
            'type' => 'relation',
            'relation' => 'assignments',
        ], [
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'content',
            'label' => 'Submission',
            'type' => 'textarea',
        ], [
            'name' => 'submitted_at',
            'label' => 'Submitted at',
            'type' => 'date',
            'optional' => true,
        ], [
            'name' => 'status',
            'label' => 'Review status',
            'type' => 'select',
            'choices' => ['submitted', 'returned'],
        ], [
            'name' => 'grade',
            'label' => 'Grade %',
            'type' => 'decimal',
            'min' => 0,
            'max' => 100,
            'optional' => true,
        ], [
            'name' => 'feedback',
            'label' => 'Teacher feedback',
            'type' => 'textarea',
            'optional' => true,
        ]],
    ],
    'assignments' => [
        'label' => 'Assignments',
        'singular' => 'assignment',
        'help' => 'Create class and subject work, set a due date, and publish it when students should see it.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin', 'teacher'],
        'fields' => [[
            'name' => 'class_id',
            'label' => 'Class',
            'type' => 'relation',
            'relation' => 'classes',
        ], [
            'name' => 'subject_id',
            'label' => 'Subject',
            'type' => 'relation',
            'relation' => 'subjects',
        ], [
            'name' => 'teacher_id',
            'label' => 'Teacher account',
            'type' => 'relation',
            'relation' => 'users',
        ], [
            'name' => 'title',
            'label' => 'Title',
            'type' => 'text',
        ], [
            'name' => 'description',
            'label' => 'Instructions',
            'type' => 'textarea',
        ], [
            'name' => 'due_on',
            'label' => 'Due date',
            'type' => 'date',
        ], [
            'name' => 'status',
            'label' => 'Visibility',
            'type' => 'select',
            'choices' => ['draft', 'published'],
        ]],
    ],
    'events' => [
        'label' => 'Events', 'singular' => 'event', 'help' => 'Publish school events and let families confirm whether they will attend.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'], 'write' => ['owner', 'admin'],
        'fields' => [[ 'name' => 'title', 'label' => 'Title', 'type' => 'text' ], [ 'name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'optional' => true ], [ 'name' => 'event_date', 'label' => 'Date', 'type' => 'date' ], [ 'name' => 'starts_at', 'label' => 'Start time', 'type' => 'time', 'optional' => true ], [ 'name' => 'ends_at', 'label' => 'End time', 'type' => 'time', 'optional' => true ], [ 'name' => 'location', 'label' => 'Location', 'type' => 'text', 'optional' => true ], [ 'name' => 'audience', 'label' => 'Audience', 'type' => 'select', 'choices' => ['all', 'students', 'parents', 'teachers'] ], [ 'name' => 'status', 'label' => 'Visibility', 'type' => 'select', 'choices' => ['draft', 'published'] ]],
    ],
    'event_rsvps' => [
        'label' => 'Event responses', 'singular' => 'response', 'help' => 'Confirm attendance for events shared with your account.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'], 'write' => ['student', 'parent', 'teacher'],
        'fields' => [[ 'name' => 'event_id', 'label' => 'Event', 'type' => 'relation', 'relation' => 'events' ], [ 'name' => 'response', 'label' => 'Response', 'type' => 'select', 'choices' => ['attending', 'not_attending', 'maybe'] ]],
    ],
    'subject_attendance' => [
        'label' => 'Subject attendance',
        'singular' => 'subject attendance record',
        'help' => 'Record attendance for a particular subject or lesson. The daily attendance register remains separate.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin', 'teacher'],
        'fields' => [[
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'subject_id',
            'label' => 'Subject',
            'type' => 'relation',
            'relation' => 'subjects',
        ], [
            'name' => 'date',
            'label' => 'Date',
            'type' => 'date',
        ], [
            'name' => 'status',
            'label' => 'Status',
            'type' => 'select',
            'choices' => ['present', 'absent', 'late', 'excused'],
        ], [
            'name' => 'note',
            'label' => 'Note',
            'type' => 'textarea',
            'optional' => true,
        ]],
    ],
    'attendance' => [
        'label' => 'Attendance',
        'singular' => 'attendance record',
        'help' => 'Choose a student, date and status. One record is allowed per student per day. Teachers can correct today’s records; administrators handle older corrections.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin', 'teacher'],
        'fields' => [[
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'date',
            'label' => 'Date',
            'type' => 'date',
        ], [
            'name' => 'status',
            'label' => 'Attendance',
            'type' => 'select',
            'choices' => ['present', 'absent', 'late', 'excused'],
        ], [
            'name' => 'note',
            'label' => 'Note',
            'type' => 'textarea',
            'optional' => true,
        ]],
    ],
    'timetables' => [
        'label' => 'Timetable',
        'singular' => 'lesson',
        'help' => 'Assign lessons to a weekday, class, subject and teacher. The system checks overlapping teacher, class and room times.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent', 'accountant'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'class_id',
            'label' => 'Class',
            'type' => 'relation',
            'relation' => 'classes',
        ], [
            'name' => 'subject_id',
            'label' => 'Subject',
            'type' => 'relation',
            'relation' => 'subjects',
        ], [
            'name' => 'teacher_id',
            'label' => 'Teacher',
            'type' => 'relation',
            'relation' => 'users',
        ], [
            'name' => 'substitute_teacher_id',
            'label' => 'Backup teacher',
            'type' => 'relation',
            'relation' => 'users',
            'optional' => true,
        ], [
            'name' => 'weekday',
            'label' => 'Day',
            'type' => 'select',
            'choices' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        ], [
            'name' => 'starts_at',
            'label' => 'Start time',
            'type' => 'time',
        ], [
            'name' => 'ends_at',
            'label' => 'End time',
            'type' => 'time',
        ], [
            'name' => 'room',
            'label' => 'Room',
            'type' => 'text',
        ]],
    ],
    'exams' => [
        'label' => 'Exams',
        'singular' => 'exam',
        'help' => 'Announce a test or paper so families can prepare. Schedule visibility is separate from results: announcing an exam never publishes its marks.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'name',
            'label' => 'Exam name',
            'type' => 'text',
        ], [
            'name' => 'class_id',
            'label' => 'Class',
            'type' => 'relation',
            'relation' => 'classes',
        ], [
            'name' => 'date',
            'label' => 'Exam date',
            'type' => 'date',
        ], [
            'name' => 'schedule_status',
            'label' => 'Schedule visibility',
            'type' => 'select',
            'choices' => ['draft', 'announced', 'cancelled'],
            'optional' => true,
        ], [
            'name' => 'status',
            'label' => 'Results',
            'type' => 'select',
            'choices' => ['draft', 'published'],
        ]],
    ],
    'grade_bands' => [
        'label' => 'Grading rules', 'singular' => 'grade band',
        'help' => 'Define grade labels, minimum percentages and GPA points. Add a band starting at 0 to cover all results. Each band extends up to the next threshold. Published exams retain a copy of these rules.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'], 'write' => ['owner', 'admin'],
        'fields' => [
            ['name' => 'name', 'label' => 'Grade label', 'type' => 'text'],
            ['name' => 'minimum', 'label' => 'Minimum percentage', 'type' => 'decimal', 'max' => 100],
            ['name' => 'gpa', 'label' => 'GPA points', 'type' => 'decimal', 'max' => 10],
        ],
    ],
    'exam_subjects' => [
        'label' => 'Exam subject plans', 'singular' => 'exam subject plan',
        'help' => 'Plan every subject before entering marks. Set the maximum marks and relative weight. Equal weights count equally. Published exam plans are locked; missing subject marks make the report incomplete.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'], 'write' => ['owner', 'admin'],
        'fields' => [
            ['name' => 'exam_id', 'label' => 'Exam', 'type' => 'relation', 'relation' => 'exams'],
            ['name' => 'subject_id', 'label' => 'Subject', 'type' => 'relation', 'relation' => 'subjects'],
            ['name' => 'maximum', 'label' => 'Maximum marks', 'type' => 'decimal', 'min' => 0.01],
            ['name' => 'weight', 'label' => 'Relative weight', 'type' => 'decimal', 'min' => 0.01, 'max' => 1000],
        ],
    ],
    'grades' => [
        'label' => 'Marks & results',
        'singular' => 'mark',
        'help' => 'Enter marks for an exam and subject. Marks cannot exceed the maximum. Published exams are locked until an administrator returns them to draft.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent'],
        'write' => ['owner', 'admin', 'teacher'],
        'fields' => [[
            'name' => 'exam_id',
            'label' => 'Exam',
            'type' => 'relation',
            'relation' => 'exams',
        ], [
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'subject_id',
            'label' => 'Subject',
            'type' => 'relation',
            'relation' => 'subjects',
        ], [
            'name' => 'marks',
            'label' => 'Marks obtained',
            'type' => 'decimal',
        ], [
            'name' => 'maximum',
            'label' => 'Maximum marks',
            'type' => 'decimal',
        ], [
            'name' => 'remarks',
            'label' => 'Remarks',
            'type' => 'textarea',
            'optional' => true,
        ]],
    ],
    'invoices' => [
        'label' => 'Fee invoices',
        'singular' => 'invoice',
        'help' => 'Create an invoice for a student. Record received payments in Payments; balances are calculated automatically. Amounts cannot change after payments are recorded.',
        'read' => ['owner', 'admin', 'accountant', 'parent', 'student'],
        'write' => ['owner', 'admin', 'accountant'],
        'fields' => [[
            'name' => 'reference',
            'label' => 'Invoice number',
            'type' => 'text',
        ], [
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'description',
            'label' => 'Description',
            'type' => 'text',
        ], [
            'name' => 'amount',
            'label' => 'Amount',
            'type' => 'money',
        ], [
            'name' => 'due_on',
            'label' => 'Due date',
            'type' => 'date',
        ], [
            'name' => 'billing_month',
            'label' => 'Fee month (leave empty for one-off fees)',
            'type' => 'month',
            'optional' => true,
        ]],
    ],
    'fee_concessions' => [
        'label' => 'Scholarships & concessions',
        'singular' => 'fee concession',
        'help' => 'Give an individual student a percentage or fixed monthly fee concession. The largest active concession is applied automatically when that month’s invoice is generated.',
        'read' => ['owner', 'admin', 'accountant'],
        'write' => ['owner', 'admin', 'accountant'],
        'fields' => [[
            'name' => 'student_id',
            'label' => 'Student',
            'type' => 'relation',
            'relation' => 'students',
        ], [
            'name' => 'name',
            'label' => 'Scholarship or concession name',
            'type' => 'text',
        ], [
            'name' => 'type',
            'label' => 'Calculation',
            'type' => 'select',
            'choices' => ['percentage', 'fixed'],
        ], [
            'name' => 'value',
            'label' => 'Value',
            'type' => 'decimal',
            'min' => 0.01,
            'max' => 100000000,
        ], [
            'name' => 'starts_on',
            'label' => 'Starts on',
            'type' => 'date',
            'optional' => true,
        ], [
            'name' => 'ends_on',
            'label' => 'Ends on',
            'type' => 'date',
            'optional' => true,
        ], [
            'name' => 'status',
            'label' => 'Status',
            'type' => 'select',
            'choices' => ['active', 'inactive'],
        ]],
    ],
    'fee_plans' => [
        'label' => 'Class fee plans',
        'singular' => 'fee plan',
        'help' => 'Set a monthly fee for a class. Active class plans override the school-wide monthly fee when automatic invoices are generated.',
        'read' => ['owner', 'admin', 'accountant'],
        'write' => ['owner', 'admin', 'accountant'],
        'fields' => [[
            'name' => 'class_id', 'label' => 'Class', 'type' => 'relation', 'relation' => 'classes',
        ], [
            'name' => 'name', 'label' => 'Plan name', 'type' => 'text',
        ], [
            'name' => 'amount', 'label' => 'Monthly amount', 'type' => 'money',
        ], [
            'name' => 'due_day', 'label' => 'Due day (1-28)', 'type' => 'number', 'min' => 1, 'max' => 28,
        ], [
            'name' => 'status', 'label' => 'Status', 'type' => 'select', 'choices' => ['active', 'inactive'],
        ]],
    ],
    'payments' => [
        'label' => 'Payments & receipts',
        'singular' => 'payment',
        'help' => 'Record a payment only after the school has received it. A unique receipt reference prevents duplicates. Recorded payments cannot be edited or deleted.',
        'read' => ['owner', 'admin', 'accountant', 'parent', 'student'],
        'write' => ['owner', 'admin', 'accountant'],
        'immutable' => true,
        'fields' => [[
            'name' => 'invoice_id',
            'label' => 'Invoice',
            'type' => 'relation',
            'relation' => 'invoices',
        ], [
            'name' => 'reference',
            'label' => 'Receipt reference',
            'type' => 'text',
        ], [
            'name' => 'amount',
            'label' => 'Amount received',
            'type' => 'money',
        ], [
            'name' => 'paid_on',
            'label' => 'Payment date',
            'type' => 'date',
        ], [
            'name' => 'method',
            'label' => 'Method',
            'type' => 'select',
            'choices' => ['cash', 'bank_transfer', 'cheque', 'online_manual'],
        ], [
            'name' => 'note',
            'label' => 'Note',
            'type' => 'textarea',
            'optional' => true,
        ]],
    ],
    'expenses' => [
        'label' => 'Expenses',
        'singular' => 'expense',
        'help' => 'Record school operating expenses with a reference and category for review.',
        'read' => ['owner', 'admin', 'accountant'],
        'write' => ['owner', 'admin', 'accountant'],
        'fields' => [[
            'name' => 'reference',
            'label' => 'Reference',
            'type' => 'text',
        ], [
            'name' => 'description',
            'label' => 'Description',
            'type' => 'text',
        ], [
            'name' => 'category',
            'label' => 'Category',
            'type' => 'text',
        ], [
            'name' => 'amount',
            'label' => 'Amount',
            'type' => 'money',
        ], [
            'name' => 'paid_on',
            'label' => 'Date',
            'type' => 'date',
        ]],
    ],
    'leave_requests' => [
        'label' => 'Staff leave',
        'singular' => 'leave request',
        'help' => 'Staff can request leave. Administrators approve or reject requests. Overlapping requests are not allowed.',
        'read' => ['owner', 'admin', 'teacher', 'accountant'],
        'write' => ['owner', 'admin', 'teacher', 'accountant'],
        'fields' => [[
            'name' => 'user_id',
            'label' => 'Staff member',
            'type' => 'relation',
            'relation' => 'users',
        ], [
            'name' => 'starts_on',
            'label' => 'First day',
            'type' => 'date',
        ], [
            'name' => 'ends_on',
            'label' => 'Last day',
            'type' => 'date',
        ], [
            'name' => 'reason',
            'label' => 'Reason',
            'type' => 'textarea',
        ], [
            'name' => 'status',
            'label' => 'Decision',
            'type' => 'select',
            'choices' => ['pending', 'approved', 'rejected'],
        ]],
    ],
    'payroll' => [
        'label' => 'Payroll records',
        'singular' => 'payroll record',
        'help' => 'Record a monthly payroll calculation. Net pay is basic pay plus allowances minus deductions. Each staff member can have one record per month.',
        'read' => ['owner', 'admin', 'accountant', 'teacher'],
        'write' => ['owner', 'admin', 'accountant'],
        'immutable' => true,
        'fields' => [[
            'name' => 'staff_id',
            'label' => 'Staff member',
            'type' => 'relation',
            'relation' => 'staff',
        ], [
            'name' => 'month',
            'label' => 'Month',
            'type' => 'month',
        ], [
            'name' => 'basic',
            'label' => 'Basic pay',
            'type' => 'money',
        ], [
            'name' => 'allowances',
            'label' => 'Allowances',
            'type' => 'money',
        ], [
            'name' => 'deductions',
            'label' => 'Deductions',
            'type' => 'money',
        ]],
    ],
    'payroll_payments' => [
        'label' => 'Salary payments',
        'singular' => 'salary payment',
        'help' => 'Record money actually paid against a monthly payroll record. Choose cash, bank transfer, cheque or online manual after independently verifying payment. Partial payments reduce the balance. Posted payments cannot be edited.',
        'read' => ['owner', 'admin', 'accountant', 'teacher'],
        'write' => ['owner', 'admin', 'accountant'],
        'immutable' => true,
        'fields' => [
            ['name' => 'payroll_id', 'label' => 'Monthly payroll', 'type' => 'relation', 'relation' => 'payroll'],
            ['name' => 'reference', 'label' => 'Payment reference', 'type' => 'text'],
            ['name' => 'amount', 'label' => 'Amount paid', 'type' => 'money'],
            ['name' => 'paid_on', 'label' => 'Payment date', 'type' => 'date'],
            ['name' => 'method', 'label' => 'Method', 'type' => 'select', 'choices' => ['cash', 'bank_transfer', 'cheque', 'online_manual']],
            ['name' => 'note', 'label' => 'Note', 'type' => 'textarea', 'optional' => true],
        ],
    ],
    'notices' => [
        'label' => 'Noticeboard',
        'singular' => 'notice',
        'help' => 'Publish announcements for everyone or for a particular role. Draft notices are visible only to administrators.',
        'read' => ['owner', 'admin', 'teacher', 'student', 'parent', 'accountant'],
        'write' => ['owner', 'admin'],
        'fields' => [[
            'name' => 'title',
            'label' => 'Title',
            'type' => 'text',
        ], [
            'name' => 'body',
            'label' => 'Message',
            'type' => 'textarea',
        ], [
            'name' => 'audience',
            'label' => 'Audience',
            'type' => 'select',
            'choices' => ['all', 'teacher', 'student', 'parent', 'accountant'],
        ], [
            'name' => 'status',
            'label' => 'Visibility',
            'type' => 'select',
            'choices' => ['draft', 'published'],
        ]],
    ],
];
